FROM golang:1.24-alpine AS builder
ENV GOMEMLIMIT=1GiB
ENV GOGC=20

WORKDIR /app
RUN apk add --no-cache git

COPY go.work go.work.sum ./
COPY libs/ ./libs/
COPY cmd/pmaxis/ ./cmd/pmaxis/
COPY services/ ./services/

WORKDIR /app/services/ingestion
RUN go build -p 1 -o /ingestion-hub .

FROM golang:1.24-alpine
ENV GOMEMLIMIT=1GiB
ENV GOGC=20
COPY --from=builder /ingestion-hub /ingestion-hub
CMD ["/ingestion-hub"]
